# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pythoncode\19.信息台账管理10.0\images\del_beta5.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_del_form(object):
    def setupUi(self, del_form):
        del_form.setObjectName("del_form")
        del_form.resize(360, 540)
        del_form.setStyleSheet("#del_form{\n"
"image: url(:/添加窗口.png);\n"
"}")
        self.title_label = QtWidgets.QLabel(del_form)
        self.title_label.setGeometry(QtCore.QRect(70, 30, 211, 51))
        font = QtGui.QFont()
        font.setFamily("方正大黑简体")
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLable{\n"
"font-color:rgb(255,255,255);\n"
"}")
        self.title_label.setObjectName("title_label")
        self.user_label = QtWidgets.QLabel(del_form)
        self.user_label.setEnabled(True)
        self.user_label.setGeometry(QtCore.QRect(34, 104, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_label.setFont(font)
        self.user_label.setStyleSheet("")
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(del_form)
        self.user_lineEdit.setGeometry(QtCore.QRect(144, 104, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setText("")
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.dept_lineEdit = QtWidgets.QLineEdit(del_form)
        self.dept_lineEdit.setGeometry(QtCore.QRect(144, 154, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dept_lineEdit.setFont(font)
        self.dept_lineEdit.setObjectName("dept_lineEdit")
        self.dept_label = QtWidgets.QLabel(del_form)
        self.dept_label.setGeometry(QtCore.QRect(34, 154, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dept_label.setFont(font)
        self.dept_label.setObjectName("dept_label")
        self.del_btn = QtWidgets.QPushButton(del_form)
        self.del_btn.setGeometry(QtCore.QRect(27, 480, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.del_btn.setFont(font)
        self.del_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,50%)\n"
"}")
        self.del_btn.setObjectName("del_btn")
        self.cancel_btn = QtWidgets.QPushButton(del_form)
        self.cancel_btn.setGeometry(QtCore.QRect(190, 480, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,50%)\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.mac_label = QtWidgets.QLabel(del_form)
        self.mac_label.setGeometry(QtCore.QRect(34, 254, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mac_label.setFont(font)
        self.mac_label.setObjectName("mac_label")
        self.ip_label = QtWidgets.QLabel(del_form)
        self.ip_label.setGeometry(QtCore.QRect(34, 204, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ip_label.setFont(font)
        self.ip_label.setObjectName("ip_label")
        self.mac_lineEdit = QtWidgets.QLineEdit(del_form)
        self.mac_lineEdit.setGeometry(QtCore.QRect(144, 254, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mac_lineEdit.setFont(font)
        self.mac_lineEdit.setText("")
        self.mac_lineEdit.setObjectName("mac_lineEdit")
        self.ip_lineEdit = QtWidgets.QLineEdit(del_form)
        self.ip_lineEdit.setGeometry(QtCore.QRect(144, 204, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ip_lineEdit.setFont(font)
        self.ip_lineEdit.setText("")
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.room_lineEdit = QtWidgets.QLineEdit(del_form)
        self.room_lineEdit.setGeometry(QtCore.QRect(144, 304, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.room_lineEdit.setFont(font)
        self.room_lineEdit.setText("")
        self.room_lineEdit.setObjectName("room_lineEdit")
        self.room_label = QtWidgets.QLabel(del_form)
        self.room_label.setGeometry(QtCore.QRect(34, 304, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.room_label.setFont(font)
        self.room_label.setObjectName("room_label")
        self.switch_label = QtWidgets.QLabel(del_form)
        self.switch_label.setGeometry(QtCore.QRect(34, 354, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.switch_label.setFont(font)
        self.switch_label.setObjectName("switch_label")
        self.switch_lineEdit = QtWidgets.QLineEdit(del_form)
        self.switch_lineEdit.setGeometry(QtCore.QRect(144, 354, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.switch_lineEdit.setFont(font)
        self.switch_lineEdit.setText("")
        self.switch_lineEdit.setObjectName("switch_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(del_form)
        self.port_lineEdit.setGeometry(QtCore.QRect(144, 404, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.port_lineEdit.setFont(font)
        self.port_lineEdit.setText("")
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.port_label = QtWidgets.QLabel(del_form)
        self.port_label.setGeometry(QtCore.QRect(34, 404, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.port_label.setFont(font)
        self.port_label.setObjectName("port_label")

        self.retranslateUi(del_form)
        QtCore.QMetaObject.connectSlotsByName(del_form)
        del_form.setTabOrder(self.user_lineEdit, self.dept_lineEdit)
        del_form.setTabOrder(self.dept_lineEdit, self.ip_lineEdit)
        del_form.setTabOrder(self.ip_lineEdit, self.mac_lineEdit)
        del_form.setTabOrder(self.mac_lineEdit, self.room_lineEdit)
        del_form.setTabOrder(self.room_lineEdit, self.switch_lineEdit)
        del_form.setTabOrder(self.switch_lineEdit, self.port_lineEdit)
        del_form.setTabOrder(self.port_lineEdit, self.del_btn)
        del_form.setTabOrder(self.del_btn, self.cancel_btn)

    def retranslateUi(self, del_form):
        _translate = QtCore.QCoreApplication.translate
        del_form.setWindowTitle(_translate("del_form", "Form"))
        self.title_label.setText(_translate("del_form", "删 除 当 前 员 工"))
        self.user_label.setText(_translate("del_form", "姓    名："))
        self.dept_label.setText(_translate("del_form", "部    门："))
        self.del_btn.setText(_translate("del_form", "确 认 删 除"))
        self.cancel_btn.setText(_translate("del_form", "取 消 操 作"))
        self.mac_label.setText(_translate("del_form", "MAC 地址："))
        self.ip_label.setText(_translate("del_form", "IP 地 址："))
        self.room_label.setText(_translate("del_form", "房间编号："))
        self.switch_label.setText(_translate("del_form", "交换机地址："))
        self.port_label.setText(_translate("del_form", "交换机端口："))

import pic_rc
