# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pythoncode\19.信息台账管理10.0\images\register_beta5.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_register_window(object):
    def setupUi(self, register_window):
        register_window.setObjectName("register_window")
        register_window.resize(640, 400)
        register_window.setStyleSheet("#register_window{\n"
"    image: url(:/register_bg.png);\n"
"}")
        self.user_label = QtWidgets.QLabel(register_window)
        self.user_label.setGeometry(QtCore.QRect(80, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_label.setFont(font)
        self.user_label.setTextFormat(QtCore.Qt.AutoText)
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(register_window)
        self.user_lineEdit.setGeometry(QtCore.QRect(190, 130, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setTabletTracking(True)
        self.user_lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(255, 255, 255, 90%)\n"
"}")
        self.user_lineEdit.setText("")
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.passwd_lineEdit = QtWidgets.QLineEdit(register_window)
        self.passwd_lineEdit.setGeometry(QtCore.QRect(190, 180, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.passwd_lineEdit.setFont(font)
        self.passwd_lineEdit.setTabletTracking(True)
        self.passwd_lineEdit.setText("")
        self.passwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.passwd_label = QtWidgets.QLabel(register_window)
        self.passwd_label.setGeometry(QtCore.QRect(80, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwd_label.setFont(font)
        self.passwd_label.setTextFormat(QtCore.Qt.AutoText)
        self.passwd_label.setObjectName("passwd_label")
        self.goback_btn = QtWidgets.QPushButton(register_window)
        self.goback_btn.setGeometry(QtCore.QRect(80, 280, 71, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.goback_btn.setFont(font)
        self.goback_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255,50%)\n"
"}")
        self.goback_btn.setDefault(False)
        self.goback_btn.setFlat(False)
        self.goback_btn.setObjectName("goback_btn")
        self.register_btn = QtWidgets.QPushButton(register_window)
        self.register_btn.setGeometry(QtCore.QRect(180, 280, 71, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 50%)\n"
"}")
        self.register_btn.setDefault(False)
        self.register_btn.setFlat(False)
        self.register_btn.setObjectName("register_btn")
        self.quit_btn = QtWidgets.QPushButton(register_window)
        self.quit_btn.setGeometry(QtCore.QRect(280, 280, 71, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_btn.setFont(font)
        self.quit_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 50%)\n"
"}")
        self.quit_btn.setDefault(False)
        self.quit_btn.setFlat(False)
        self.quit_btn.setObjectName("quit_btn")
        self.version_label = QtWidgets.QLabel(register_window)
        self.version_label.setGeometry(QtCore.QRect(490, 370, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.confirm_label = QtWidgets.QLabel(register_window)
        self.confirm_label.setGeometry(QtCore.QRect(80, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirm_label.setFont(font)
        self.confirm_label.setTextFormat(QtCore.Qt.AutoText)
        self.confirm_label.setObjectName("confirm_label")
        self.confirm_lineEdit = QtWidgets.QLineEdit(register_window)
        self.confirm_lineEdit.setGeometry(QtCore.QRect(190, 230, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.confirm_lineEdit.setFont(font)
        self.confirm_lineEdit.setTabletTracking(True)
        self.confirm_lineEdit.setText("")
        self.confirm_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_lineEdit.setObjectName("confirm_lineEdit")

        self.retranslateUi(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)
        register_window.setTabOrder(self.user_lineEdit, self.passwd_lineEdit)
        register_window.setTabOrder(self.passwd_lineEdit, self.confirm_lineEdit)
        register_window.setTabOrder(self.confirm_lineEdit, self.register_btn)
        register_window.setTabOrder(self.register_btn, self.goback_btn)
        register_window.setTabOrder(self.goback_btn, self.quit_btn)

    def retranslateUi(self, register_window):
        _translate = QtCore.QCoreApplication.translate
        register_window.setWindowTitle(_translate("register_window", "账号注册"))
        self.user_label.setText(_translate("register_window", "账    号："))
        self.passwd_label.setText(_translate("register_window", "密    码："))
        self.goback_btn.setText(_translate("register_window", "返回登录"))
        self.register_btn.setText(_translate("register_window", "注   册"))
        self.quit_btn.setText(_translate("register_window", "退   出"))
        self.version_label.setText(_translate("register_window", "version:beta4 20200510"))
        self.confirm_label.setText(_translate("register_window", "确认密码："))

import pic_rc
