# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\datacode\6.ui_files\add_em_beta2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys



class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 452)
        self.welcome_label = QtWidgets.QLabel(Dialog)
        self.welcome_label.setGeometry(QtCore.QRect(120, 40, 141, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.user_label = QtWidgets.QLabel(Dialog)
        self.user_label.setGeometry(QtCore.QRect(50, 123, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.user_lineEdit.setGeometry(QtCore.QRect(170, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.dept_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.dept_lineEdit.setGeometry(QtCore.QRect(170, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dept_lineEdit.setFont(font)
        self.dept_lineEdit.setObjectName("dept_lineEdit")
        self.dept_label = QtWidgets.QLabel(Dialog)
        self.dept_label.setGeometry(QtCore.QRect(50, 183, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.dept_label.setFont(font)
        self.dept_label.setObjectName("dept_label")
        self.ip_label = QtWidgets.QLabel(Dialog)
        self.ip_label.setGeometry(QtCore.QRect(50, 243, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.ip_label.setFont(font)
        self.ip_label.setObjectName("ip_label")
        self.ip_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.ip_lineEdit.setGeometry(QtCore.QRect(170, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ip_lineEdit.setFont(font)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.mac_label = QtWidgets.QLabel(Dialog)
        self.mac_label.setGeometry(QtCore.QRect(50, 303, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.mac_label.setFont(font)
        self.mac_label.setObjectName("mac_label")
        self.mac_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.mac_lineEdit.setGeometry(QtCore.QRect(170, 310, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mac_lineEdit.setFont(font)
        self.mac_lineEdit.setObjectName("mac_lineEdit")
        self.confirm_label = QtWidgets.QPushButton(Dialog)
        self.confirm_label.setGeometry(QtCore.QRect(40, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirm_label.setFont(font)
        self.confirm_label.setObjectName("confirm_label")
        self.cancel_label = QtWidgets.QPushButton(Dialog)
        self.cancel_label.setGeometry(QtCore.QRect(150, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancel_label.setFont(font)
        self.cancel_label.setObjectName("cancel_label")
        self.quit_label = QtWidgets.QPushButton(Dialog)
        self.quit_label.setGeometry(QtCore.QRect(260, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quit_label.setFont(font)
        self.quit_label.setObjectName("quit_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_label.setText(_translate("Dialog", "添 加 员 工"))
        self.user_label.setText(_translate("Dialog", "用户名称："))
        self.user_lineEdit.setText(_translate("Dialog", "aaaa-aaaa-aaaa"))
        self.dept_lineEdit.setText(_translate("Dialog", "aaaa-aaaa-aaaa"))
        self.dept_label.setText(_translate("Dialog", "部门名称："))
        self.ip_label.setText(_translate("Dialog", "IP地址："))
        # self.ip_lineEdit.setText(_translate("Dialog", "aaaa-aaaa-aaaa"))
        self.mac_label.setText(_translate("Dialog", "MAC地址："))
        self.mac_lineEdit.setText(_translate("Dialog", "aaaa-aaaa-aaaa"))
        self.confirm_label.setText(_translate("Dialog", "确 认"))
        self.cancel_label.setText(_translate("Dialog", "取 消"))
        self.quit_label.setText(_translate("Dialog", "退 出"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ud = Ui_Dialog()
    ud.setupUi(ud)
    ud.show()
    sys.exit(app.exec_())
