# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pythoncode\6.ui_files\query_beta3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 347)
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(150, 60, 171, 51))
        font = QtGui.QFont()
        font.setFamily("方正大黑简体")
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.user_label = QtWidgets.QLabel(Form)
        self.user_label.setGeometry(QtCore.QRect(100, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(Form)
        self.user_lineEdit.setGeometry(QtCore.QRect(212, 150, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.ip_lineEdit = QtWidgets.QLineEdit(Form)
        self.ip_lineEdit.setGeometry(QtCore.QRect(210, 200, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ip_lineEdit.setFont(font)
        self.ip_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.ip_label = QtWidgets.QLabel(Form)
        self.ip_label.setGeometry(QtCore.QRect(98, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ip_label.setFont(font)
        self.ip_label.setObjectName("ip_label")
        self.query_btn = QtWidgets.QPushButton(Form)
        self.query_btn.setGeometry(QtCore.QRect(95, 280, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.query_btn.setFont(font)
        self.query_btn.setObjectName("query_btn")
        self.reset_btn = QtWidgets.QPushButton(Form)
        self.reset_btn.setGeometry(QtCore.QRect(195, 280, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        self.quit_btn = QtWidgets.QPushButton(Form)
        self.quit_btn.setGeometry(QtCore.QRect(295, 280, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_btn.setFont(font)
        self.quit_btn.setObjectName("quit_btn")
        self.tip_label = QtWidgets.QLabel(Form)
        self.tip_label.setGeometry(QtCore.QRect(170, 110, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tip_label.setFont(font)
        self.tip_label.setObjectName("tip_label")
        self.name_radioButton = QtWidgets.QRadioButton(Form)
        self.name_radioButton.setGeometry(QtCore.QRect(110, 250, 101, 16))
        self.name_radioButton.setChecked(True)
        self.name_radioButton.setObjectName("name_radioButton")
        self.ip_radioButton = QtWidgets.QRadioButton(Form)
        self.ip_radioButton.setGeometry(QtCore.QRect(260, 250, 101, 16))
        self.ip_radioButton.setObjectName("ip_radioButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.user_lineEdit, self.ip_lineEdit)
        Form.setTabOrder(self.ip_lineEdit, self.name_radioButton)
        Form.setTabOrder(self.name_radioButton, self.ip_radioButton)
        Form.setTabOrder(self.ip_radioButton, self.query_btn)
        Form.setTabOrder(self.query_btn, self.reset_btn)
        Form.setTabOrder(self.reset_btn, self.quit_btn)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_label.setText(_translate("Form", "查询员工信息"))
        self.user_label.setText(_translate("Form", "姓    名："))
        self.ip_label.setText(_translate("Form", "IP 地 址："))
        self.query_btn.setText(_translate("Form", "查  询"))
        self.reset_btn.setText(_translate("Form", "重  置"))
        self.quit_btn.setText(_translate("Form", "退  出"))
        self.tip_label.setText(_translate("Form", "通过使用人或者IP查询信息"))
        self.name_radioButton.setText(_translate("Form", "通过姓名查询"))
        self.ip_radioButton.setText(_translate("Form", "通过IP查询"))
